export const pageLinks = {
  home: "/",
  docs: "/docs",
  installation: "/docs/installation",
  signup: "https://app.forgecode.dev/app/",
  pricing: "/pricing",
  // about: "/about",
  // contact: "/contact",
  contributors: "/docs/contribution-guidelines",
  privacyPolicy: "/privacy/",
  // enterprise: "/enterprise",
  about: "/about",
  blog: "/blog",
  releases: "/releases",
}
